name       : mm-common
version    : 1.0.2
release    : 2
source     :
    - https://download.gnome.org/sources/mm-common/1.0/mm-common-1.0.2.tar.xz : a2a99f3fa943cf662f189163ed39a2cfc19a428d906dd4f92b387d3659d1641d
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Utilities shared among GNOME C++ binding libraries
description: |
    The mm-common module provides the build infrastructure and utilities shared among the GNOME C++ binding libraries.
patterns   : /usr/share/aclocal
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
