name       : mm-common
version    : 0.9.10
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/mm-common/0.9/mm-common-0.9.10.tar.xz : 16c0e2bc196b67fbc145edaecb5dbe5818386504fe5703de27002d77140fa217
license    : GPL-2.0
component  : programming
summary    : Utilities shared among GNOME C++ binding libraries
description: |
    The mm-common module provides the build infrastructure and utilities shared among the GNOME C++ binding libraries.
patterns  : /usr/share/aclocal
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
